[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dobot_api"
version = "3.0.0"
description = "Dobot Robot API for TCP/IP communication"
requires-python = ">=3.6"
dependencies = [
    "numpy",
]